# Generated by Django 6.0.1 on 2026-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=50, unique=True)),
                ('canvas_w', models.PositiveIntegerField(default=560)),
                ('canvas_h', models.PositiveIntegerField(default=480)),
                ('shoulder_radius', models.PositiveIntegerField(default=22)),
                ('bullet_radius', models.PositiveIntegerField(default=9)),
                ('base_interval', models.PositiveIntegerField(default=1200)),
                ('speed_base', models.FloatField(default=4.0)),
                ('lives_max', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Anonymous', max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
